# Laborator 3

Saptamana 11-15 martie 2019

## Exercitii simple folosind API de NumPy  

Nota: in rezolvarea exercitiilor se vor folosi cat mai mult functii NumPy vectorizate. Functiile scrise de voi vor fi documentate cu docstrings (tutoriale: Docstrings in Python, urmati NumPy Style Python Docstrings). Folositi type annotations. Utilizati doar pachetele NumPy si SciPy.

1. (0.5 puncte) Folosind functia `np.where`, determinati care sunt liniile si coloanele care contin un element dat intr-o matrice. 
1. (0.5 puncte) Pentru o matrice de numere, sa se determine produsul elementelor pe linii.
1. (0.5 puncte) Determinati daca toate elementele unei matrice `a` sunt mai mari sau egale decat toate de pe pozitiile corespondente din `b`.
1. (0.5 puncte) Pentru un vector de numere, care sunt *toate pozitiile* pe care apare valoarea maxima? Folositi functie NumPy.
1. (0.5 puncte) Se considera vectorul: `a = np.array([230, 10, 284, 39, 76])`. Folosind indexarea logica, sa se inmulteasca elementele din vector care sunt mai mici ca 100 cu 2 (restul raman neschimbate). Folosind ciclare, sa se aplice aceeasi operatie pana cand toate elementele devin mai mari ca 100. Sa se afiseze din vectorul final elementele care sunt mai mari de 150 si mai mici de 200.
1. (0.5 puncte) Sa se scrie o functie care preia doi vectori de aceeasi lungime si returneaza maximele pe pozitiile corespunzatoare:
```python
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
pair_max(a, b)
#iesire dorita: 
array([  4,   7,   9, 100, 300, 230,   3])
```
1. (1 punct) Sa se calculeze suma elementelor non-NaN intr-un 2d numpy array, in 3 feluri. Folosind comanda magica `%%timeit` [Built-in magic commands](http://ipython.readthedocs.io/en/stable/interactive/magics.html#cell-magics), [IPython Magic Commands](https://jakevdp.github.io/PythonDataScienceHandbook/01.03-magic-commands.html), sa se determine care e mai rapida.
    1. Peste o copie a tabelului initial (functia membru `copy()` a unui tablou) se suprascriu elementele nan cu 0, apoi se face suma;
    1. Folosind functia `np.nansum`;
    1. Folosind indiciere booleana si functia `np.isnan`, se determina colectia elementelor non-nan si se calculeaza suma lor in mod obisnuit.
1. (1 punct) Incarcati setul de date Iris, de la adresa 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', folosind `np.genfromtxt`.  Alegeti aleator 10 pozitii in matricea de 150 linii si 4 coloane (omiteti ultima coloana, de tip text), setati aceste valori pe NaN. Construiti o functie care, primid la intrare o matrice, returneaza un tuplu cu indicii de linie respectiv de coloana in care se gasesc valori NaN.
1. (1 punct) Construiti o functie care, primind o matrice, determina pe ce pozitii se afla valorile in afara unui interval \[min, max\] dat prin parametri. 
1. (1 punct) Sa se construiasca o functie care returneaza cele mai mari `k` valori dintr-un vector de cel putin `k` elemente, impreuna cu pozitiile lor. 

**Precizari:**
1. Se acorda 3 puncte din oficiu.
1. Tema se va prezenta in sapatamana 18-22 martie. 
1. Modalitatea de predare a temei: 
    1. se vor forma si se va lucra in echipe de cate doua persoane (in cazul in care nu se poate, se va lucra individual)
    2. exercitiile rezolvate se vor comite pe un repository **privat** de [Github](https://github.com/), la care vor avea doar acces membrii echipei si profesorii, Lucian Mircea Sasu (cont github: lmsasu) respectiv Arpad Kerestely (cont github: akerestely)
    3. repository-ul va contine un fisier "readme.md" (in radacina repository-ului) in care vor fi mentionati autorii temelor, cu nume complet si grupa din care fac parte.

## Importuri.

In [1]:
import numpy as np

## Rezolvari.

1. (0.5 puncte) Folosind functia `np.where`, determinati care sunt liniile si coloanele care contin un element dat intr-o matrice. 

In [2]:
def find_element_in_matrix(matrix :np.matrix, element :float) -> None:
    '''
    Prints all the positions of an element found in a matrix.
    params      : matrix  : np.matrix, the given matrix;
                  element : the element to be found.
    return      : None
    '''
    row, column = np.where(matrix == element)
    print(row, column)
    
find_element_in_matrix(np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), 3)

[0] [2]


2. (0.5 puncte) Pentru o matrice de numere, sa se determine produsul elementelor pe linii.

In [3]:
def multiply_elem_row(matrix :np.matrix) -> None:
    '''
    Makes the prod to the elements of each row
    params      : matrix  : np.matrix, the given matrix;
    return      : None
    '''
    line_res = np.prod(matrix, axis=1)
    print(line_res)
    
multiply_elem_row(np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

[[  6]
 [120]
 [504]]


3. (0.5 puncte) Determinati daca toate elementele unei matrice `a` sunt mai mari sau egale decat toate de pe pozitiile corespondente din `b`.

In [4]:
def find_elements_grater(a :np.matrix, b :np.matrix) -> bool:
    '''
    Finds if all the elements of both matrices are are greater or at least equal to the first matrix 'a'
    params   : a, b both type np.matrix
    return   : None
    '''
    return a.any() < b.any()
        
find_elements_grater(np.matrix([[1, 2, 3], [4, 5, 6], [2, 8, 9]]), np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

False

4. (0.5 puncte) Pentru un vector de numere, care sunt *toate pozitiile* pe care apare valoarea maxima? Folositi functie NumPy.

In [5]:
def find_poz_max_elem(numbers :np.array) -> np.ndarray:
    '''
    Returns np.ndarray containing the index of max element
    param    : numbers a np.array of numbers
    return   : np.ndarray containing the index of max element
    '''
    return np.where(numbers == np.max(numbers))
    
find_poz_max_elem(np.array([1, 3, 2, 8, 1]))

(array([3], dtype=int64),)

5. (0.5 puncte) Se considera vectorul: `a = np.array([230, 10, 284, 39, 76])`. Folosind indexarea logica, sa se inmulteasca elementele din vector care sunt mai mici ca 100 cu 2 (restul raman neschimbate). Folosind ciclare, sa se aplice aceeasi operatie pana cand toate elementele devin mai mari ca 100. Sa se afiseze din vectorul final elementele care sunt mai mari de 150 si mai mici de 200.

In [6]:
def logical_index(a :np.array) -> None:
    '''
    Modifies the matrix in a way, numbers that are smaller than 100 will get mmultiplyed by 2
    Repeat this untill no numbers with this condition are left
    Print the resulting np.array only with elements between 150 and 200
    params    : a, np.array, the given array made of numbers
    return    : None
    '''
    while a[a < 100].any():
        a[a < 100] = a[a < 100] * 2
        print(a)
    print(a[(a > 150) & (a < 200)])
    
a = np.array([230, 10, 284, 39, 76])
logical_index(a)

[230  20 284  78 152]
[230  40 284 156 152]
[230  80 284 156 152]
[230 160 284 156 152]
[160 156 152]


6. (0.5 puncte) Sa se scrie o functie care preia doi vectori de aceeasi lungime si returneaza maximele pe pozitiile corespunzatoare:
```python
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
pair_max(a, b)
#iesire dorita: 
array([  4,   7,   9, 100, 300, 230,   3])
```

In [7]:
def pair_max(a :np.array, b :np.array) -> np.array:
    '''
    Return the maximum a and b depending on position
    params    : a, np.array, the first given array of numbers
                b, np.array, the second given array of numbers
    return    : np.array made of maximum of each index on both arrays
    '''
    return np.maximum(a, b)
    
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
pair_max(a, b) == np.array([  4,   7,   9, 100, 300, 230,   3])

array([ True,  True,  True,  True,  True,  True,  True])

7. (1 punct) Sa se calculeze suma elementelor non-NaN intr-un 2d numpy array, in 3 feluri. Folosind comanda magica `%%timeit` [Built-in magic commands](http://ipython.readthedocs.io/en/stable/interactive/magics.html#cell-magics), [IPython Magic Commands](https://jakevdp.github.io/PythonDataScienceHandbook/01.03-magic-commands.html), sa se determine care e mai rapida.
    1. Peste o copie a tabelului initial (functia membru `copy()` a unui tablou) se suprascriu elementele nan cu 0, apoi se face suma;
    1. Folosind functia `np.nansum`;
    1. Folosind indiciere booleana si functia `np.isnan`, se determina colectia elementelor non-nan si se calculeaza suma lor in mod obisnuit.

A. Peste o copie a tabelului initial (functia membru `copy()` a unui tablou) se suprascriu elementele nan cu 0, apoi se face suma;

In [8]:
%%timeit
def copy_sum(matrix :np.matrix) -> None:
    '''
    Dose the sum of elements of matrix
    params    : matrix, type np.matrix, given matrix
    return    : None
    '''
    np.sum(np.nan_to_num(matrix))
    
copy_sum(np.matrix([[1, 2, 3], [np.nan, 5, 6], [7, 8, 9]]))

47.8 µs ± 948 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


B. Folosind functia `np.nansum`;

In [9]:
%%timeit
def nan_sum(matrix :np.matrix) -> None:
    '''
    Dose the sum of elements of matrix
    params    : matrix, type np.matrix, given matrix
    return    : None
    '''
    np.nansum(matrix)
    
nan_sum(np.matrix([[1, 2, 3], [np.nan, 5, 6], [7, 8, 9]]))

27.6 µs ± 290 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


C. Folosind indiciere booleana si functia `np.isnan`, se determina colectia elementelor non-nan si se calculeaza suma lor in mod obisnuit.

In [10]:
%%timeit
def boolean_index_sum(matrix :np.matrix) -> None:
    '''
    Dose the sum of elements of matrix
    params    : matrix, type np.matrix, given matrix
    return    : None
    '''
    np.sum(matrix[np.isnan(matrix) == False])
    
boolean_index_sum(np.matrix([[1, 2, 3], [np.nan, 5, 6], [7, 8, 9]]))

32.8 µs ± 146 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


8. (1 punct) Incarcati setul de date Iris, de la adresa 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', folosind `np.genfromtxt`.  Alegeti aleator 10 pozitii in matricea de 150 linii si 4 coloane (omiteti ultima coloana, de tip text), setati aceste valori pe NaN. Construiti o functie care, primid la intrare o matrice, returneaza un tuplu cu indicii de linie respectiv de coloana in care se gasesc valori NaN.

In [11]:
def index_of_nan(matrix :np.ndarray) -> tuple:
    '''
    Returns a tuple with the index of all NaN in a given matrix
    params    : matrix, type np.ndarray, the given matrix
    return    : a tuple with indexes
    '''
    return np.where(np.isnan(matrix))

def load_data_set() -> None:
    '''
    Loads the dataset with np.genfromtxt and inserts random NaN's in the resulting matrix
    params   : None
    return   : None
    '''
    data = np.genfromtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", delimiter=',')[:, :-1]
    data[np.random.randint(0, data.shape[0], 10), np.random.randint(0, data.shape[1], 10)] = np.nan
    result = index_of_nan(data)
    coord_list = list(zip(result[0], result[1]))
    print(data, coord_list)
    
    
load_data_set()

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 nan nan 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 nan]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [nan 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

9. (1 punct) Construiti o functie care, primind o matrice, determina pe ce pozitii se afla valorile in afara unui interval \[min, max\] dat prin parametri. 

In [12]:
def determin_index_out_of_bounds(matrix :np.matrix, minimum :int, maximum :int) -> None:
    '''
    Takes a matrix and finds all the values that are outside a given interval
    params     : matrix, np.matrix, given matrix
                 minimum, int, the lower part of interval
                 maximum, int, the upper part of interval
    return     : None
    '''
    print(np.argwhere(np.logical_or(matrix < minimum, matrix > maximum)))
    
determin_index_out_of_bounds(np.matrix([[1, 2, 3], [4, 5, 6], [2, 8, 9]]), 5, 6)

[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [2 0]
 [2 1]
 [2 2]]


10. (1 punct) Sa se construiasca o functie care returneaza cele mai mari `k` valori dintr-un vector de cel putin `k` elemente, impreuna cu pozitiile lor. 

In [13]:
def max_k_elements_with_index(numbers :np.array, k :int) -> tuple:
    '''
    Return the max values with indeces on a given array
    params    : numbers, np.array, the given array
                k, int, the number of max elements to give
    return    : tuple with position and element
    '''
    if len(numbers) >= k:
        index = np.argpartition(numbers, -k)[-k:]
        return (index, numbers[index])
    else:
        print("Can't be")
        return (0, 0)
    
print(max_k_elements_with_index(np.array([3, 7, 9, 13, -10, 200, 3]), 4))

(array([1, 2, 5, 3], dtype=int64), array([  7,   9, 200,  13]))
